title: Glorantha Perspectives
description: Ressources diverses pour explorer l'univers-jeu Glorantha
baseurl: "/glorantha-perspectives"
url: "https://aleascript.github.io"
theme: jekyll-theme-cayman
lang: fr

defaults:
  - scope:
      path: ""
    values:
      layout: default
