import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const isFrench = (process.env.DOCUSAURUS_CURRENT_LOCALE ?? 'fr') === 'fr';
const t = (fr: string, en: string) => (isFrench ? fr : en);

// Navigation is intentionally curated here: draft notes, archives, and selected
// narrative subpages should not be exposed by an autogenerated sidebar.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: t('Commencer', 'Start'),
      link: {type: 'doc', id: 'start/index'},
      items: [
        'start/vocabulary',
        {
          type: 'category',
          label: 'Glorantha',
          link: {type: 'doc', id: 'start/glorantha'},
          items: ['start/runic-imprint', 'start/calendar', 'start/currency'],
        },
        'start/table-agreement',
        'start/play-modes',
      ],
    },
    {
      type: 'category',
      label: t('Protagonistes', 'Protagonists'),
      link: {type: 'doc', id: 'protagonists/index'},
      items: ['protagonists/examples', 'perspectives/taboos/index'],
    },
    {
      type: 'category',
      label: t('Le Temps', 'Time'),
      link: {type: 'doc', id: 'time/index'},
      items: [
        'time/conduct/index',
        {
          type: 'category',
          label: 'Situations',
          link: {type: 'doc', id: 'time/situations/index'},
          items: ['time/situations/three-stones-source'],
        },
        'time/runic-inspiration/index',
      ],
    },
    {
      type: 'category',
      label: t('Perspectives', 'Perspectives'),
      link: {type: 'doc', id: 'perspectives/index'},
      items: [
        {
          type: 'category',
          label: t('Résolution', 'Resolution'),
          link: {type: 'doc', id: 'perspectives/resolution/index'},
          items: [
            'perspectives/resolution/framing',
            'perspectives/resolution/balance',
            'perspectives/resolution/reading-reality',
            'perspectives/resolution/interpretation',
          ],
        },
        {
          type: 'category',
          label: t('Mises', 'Bets'),
          link: {type: 'doc', id: 'perspectives/bets/index'},
          items: ['perspectives/bets/sample/index'],
        },
        {
          type: 'category',
          label: t('Visions du monde', 'Worldviews'),
          link: {type: 'doc', id: 'perspectives/worldviews/index'},
          items: [
            {
              type: 'category',
              label: t('Théisme', 'Theism'),
              link: {type: 'doc', id: 'perspectives/theism/index'},
              items: ['perspectives/theism/runic-cards/index'],
            },
            {
              type: 'category',
              label: t('Animisme', 'Animism'),
              link: {type: 'doc', id: 'perspectives/animism/index'},
              items: [
                'perspectives/animism/aptitudes/index',
                'perspectives/animism/spirit-bag/index',
              ],
            },
            'perspectives/logic/index',
            {
              type: 'category',
              label: t('Mysticisme', 'Mysticism'),
              link: {type: 'doc', id: 'perspectives/mysticism/index'},
              items: ['perspectives/mysticism/mystical-marbles/index'],
            },
            {
              type: 'category',
              label: t('Pensée draconique', 'Draconic Thought'),
              link: {type: 'doc', id: 'perspectives/draconic/index'},
              items: ['perspectives/draconic/ars-draconis-magica/index'],
            },
          ],
        },
        {
          type: 'category',
          label: t('Influences et transformations', 'Influences and transformations'),
          link: {type: 'doc', id: 'perspectives/influences/index'},
          items: [
            'perspectives/moon/index',
            'perspectives/illumination/index',
            {
              type: 'category',
              label: 'Chaos',
              link: {type: 'doc', id: 'perspectives/chaos/index'},
              items: ['perspectives/chaos/cosmology'],
            },
          ],
        },
        {
          type: 'category',
          label: t('Quêtes héroïques', 'Heroquests'),
          link: {type: 'doc', id: 'perspectives/heroquests/index'},
          items: [
            'perspectives/creating-myths/index',
            'perspectives/discovering-a-worldview/index',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: t('Récits', 'Narratives'),
      link: {type: 'doc', id: 'narratives/index'},
      items: [
        {
          type: 'category',
          label: t('La Voie Lunaire', 'The Lunar Way'),
          link: {type: 'doc', id: 'narratives/the-lunar-way/index'},
          items: [
            {
              type: 'category',
              label: t('Héros', 'Heroes'),
              items: [
                'narratives/the-lunar-way/heroes/jaridan/index',
                'narratives/the-lunar-way/heroes/ikarnos/index',
                'narratives/the-lunar-way/heroes/hanya/index',
                'narratives/the-lunar-way/heroes/peek-ee-peek/index',
              ],
            },
            {
              type: 'category',
              label: t('Récit', 'Story'),
              items: [
                'narratives/the-lunar-way/01/index',
                'narratives/the-lunar-way/02/index',
                'narratives/the-lunar-way/03/index',
                'narratives/the-lunar-way/04/index',
                'narratives/the-lunar-way/05/index',
                'narratives/the-lunar-way/06/index',
                'narratives/the-lunar-way/07/index',
                'narratives/the-lunar-way/08/index',
                'narratives/the-lunar-way/09/index',
                'narratives/the-lunar-way/10/index',
                'narratives/the-lunar-way/11/index',
                'narratives/the-lunar-way/12/index',
                'narratives/the-lunar-way/13/index',
                'narratives/the-lunar-way/14/index',
                'narratives/the-lunar-way/15/index',
                'narratives/the-lunar-way/16/index',
                'narratives/the-lunar-way/17/index',
              ],
            },
            'narratives/the-lunar-way/others/index',
          ],
        },
        {
          type: 'category',
          label: t('Aventures en Sartar', 'Adventures in Sartar'),
          items: [
                    {
                      type: 'category',
                      label: t('La Route de Talimar', "Talimar's Road"),
                      link: {type: 'doc', id: 'narratives/talimar-road/index'},
                      items: [
                              {
                                type: 'category',
                                label: 'Session 0',
                                link: {type: 'doc', id: 'narratives/talimar-road/session-0/index'},
                                items: [
                                  'narratives/talimar-road/session-0/verbatim',
                                  'narratives/talimar-road/session-0/narrative',
                                  'narratives/talimar-road/session-0/backstage',
                                  'narratives/talimar-road/session-0/portrait',
                                ],
                              },
                              {
                                type: 'category',
                                label: 'Session 1',
                                link: {type: 'doc', id: 'narratives/talimar-road/session-1/index'},
                                items: [
                                  'narratives/talimar-road/session-1/verbatim',
                                  'narratives/talimar-road/session-1/narrative',
                                  'narratives/talimar-road/session-1/backstage',
                                  'narratives/talimar-road/session-1/portrait',
                                ],
                              },
                              {
                                type: 'category',
                                label: 'Session 2',
                                link: {type: 'doc', id: 'narratives/talimar-road/session-2/index'},
                                items: [
                                  'narratives/talimar-road/session-2/verbatim',
                                  'narratives/talimar-road/session-2/narrative',
                                  'narratives/talimar-road/session-2/backstage',
                                  'narratives/talimar-road/session-2/portrait',
                                ],
                              },
                              {
                                type: 'category',
                                label: 'Session 3',
                                link: {type: 'doc', id: 'narratives/talimar-road/session-3/index'},
                                items: [
                                  'narratives/talimar-road/session-3/verbatim',
                                  'narratives/talimar-road/session-3/narrative',
                                  'narratives/talimar-road/session-3/backstage',
                                  'narratives/talimar-road/session-3/portrait',
                                ],
                              },
                            ],
              },
              {
                type: 'category',
                label: 'Edkored',
                link: {type: 'doc', id: 'narratives/edkored/index'},
                items: [
                  {
                    type: 'category',
                    label: 'Session 0',
                    link: {type: 'doc', id: 'narratives/edkored/session-0/index'},
                    items: [
                      'narratives/edkored/session-0/verbatim',
                      'narratives/edkored/session-0/narrative',
                      'narratives/edkored/session-0/backstage',
                      'narratives/edkored/session-0/portrait',
                    ],
                  },
                ],
              }
          ]
        }, 
        {
          type: 'category',
          label: t('Aventures en Prax', 'Adventures in Prax'),
          //link: {type: 'doc', id: 'narratives/adventures-in-prax/index'},
          items: [
            {
              type: 'category',
              label: t('La Source des Trois Pierres', 'The Three Stones Spring'),
              link: {
                type: 'doc',
                id: 'narratives/adventures-in-prax/three-stones-source/index',
              },
              items: [
                'narratives/adventures-in-prax/three-stones-source/verbatim',
                'narratives/adventures-in-prax/three-stones-source/backstage',
              ],
            },
            {
              type: 'category',
              label: t('Les Héritiers de Zola Fel', 'Heirs of Zola Fel'),
              link: {type: 'doc', id: 'narratives/heirs-of-zola-fel/index'},
              items: [
                {
                  type: 'category',
                  label: t('Héros', 'Heroes'),
                  items: [
                    'narratives/heirs-of-zola-fel/heroes/duckita/index',
                    'narratives/heirs-of-zola-fel/heroes/fazia/index',
                    'narratives/heirs-of-zola-fel/heroes/irinus/index',
                    'narratives/heirs-of-zola-fel/heroes/korlanth/index',
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: t('Éclairages', 'Insights'),
      link: {type: 'doc', id: 'insights/index'},
      items: ['insights/faq', 'insights/probabilities'],
    },
    'about/index',
    {
      type: 'link',
      label: 'Publications',
      href: '/publications/',
    },
  ],
};

export default sidebars;
